=== Veremes/rTest/scenario/rtest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="workspace" type="xs:string"/>
	<xs:element name="logfile" type="xs:string"/>
	<xs:element name="source">
		<xs:complexType>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="file"/>
						<xs:enumeration value="database"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="format" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="POSTGRES"/>
						<xs:enumeration value="ORACLE"/>
						<xs:enumeration value="SHAPE"/>
						<xs:enumeration value="FFS"/>
						<xs:enumeration value="SPATIALITE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="connection" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="dataset" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ft" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="scenario">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="author"/>
				<xs:element ref="description"/>
				<xs:element ref="fme_path"/>
				<xs:element ref="rtestCollection"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rtestCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rtest" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rtest">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enabled" minOccurs="0"/>
				<xs:element ref="deletebefore" minOccurs="0"/>
				<xs:element ref="name"/>
				<xs:element ref="processCollection"/>
				<xs:element ref="checkCollection"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="processCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="process" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="process">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="workspace"/>
				<xs:element ref="logfile" minOccurs="0"/>
				<xs:element ref="parameterCollection" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameterCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="enabled" default="true">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="deletebefore">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="fme_path">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="description">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:attribute name="expected" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="featuresCount"/>
						<xs:enumeration value="featuresCountByFtAndGeometry"/>
						<xs:enumeration value="regExp"/>
						<xs:enumeration value="attributeValue"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="attribute" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="row" use="optional" default="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="checkCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="check" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="check">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="source"/>
				<xs:element ref="condition"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Veremes/rTest/workspaces/sc_HelloWorld.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scenario [
	<!ENTITY workspaceDir ".">
	<!ENTITY fmePath "fme.exe">
]>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rtest.xsd">
	<name>Hello World !</name>
	<author>Olivier</author>
	<description>Scenario for 2017 International User Conference Vancouver</description>
	<fme_path>&fmePath;</fme_path>
	<rtestCollection>
		<rtest>
			<enabled>true</enabled>
			<deletebefore>&workspaceDir;\workspaces\result\country.sqlite</deletebefore>
			<name>Extract country by XY</name>
			<processCollection>
				<process>
					<description>XY in an aggregate</description>
					<workspace>&workspaceDir;\workspaces\HelloWorld.fmw</workspace>
					<parameterCollection>
						<parameter name="xy" value="-123.0 49.1"/>
					</parameterCollection>
				</process>
			</processCollection>
			<checkCollection>
				<check>
					<description>Number of features</description>
					<source type="file" format="SPATIALITE" dataset="&workspaceDir;\workspaces\result\country.sqlite" ft="country"/>
					<condition type="featuresCount" expected="1"/>
				</check>			
				<check>
					<description>Numb. of ft. by type + geometry</description>
					<source type="file" format="SPATIALITE" dataset="&workspaceDir;\workspaces\result\country.sqlite" ft="country"/>
					<condition type="featuresCountByFtAndGeometry" expected="country.fme_aggregate:1"/>
				</check>
				<check>
					<description>Country name</description>
					<source type="file" format="SPATIALITE" dataset="&workspaceDir;\workspaces\result\country.sqlite" ft="country"/>
					<condition type="attributeValue" attribute="name" row="1" expected="Canada"/>
				</check>
			</checkCollection>
		</rtest>
	</rtestCollection>
</scenario>
